name: flutter_fic8_final_g3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  dotted_line: ^3.2.2
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_animate: ^4.2.0+1

dev_dependencies:
  freezed: ^2.4.3
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
